spring:
  application:
    name: "Record shop"
    message: "Welcome to the Record Shop"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/recordShop?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    properties:
      temp:
        use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.MySQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

#---
#server:
#  port: 8443
#  ssl:
#    key-store: classpath:certs/keystore.p12
#    key-store-password: ${KEYSTORE_PASSWORD}
#    key-store-type: PKCS12
#    key-alias: mycert
#    ssl-protocol: TLS
#    ssl-enabled-protocols: TLSv1.2, TLSv1.3